services:
  app:
    container_name: surfscrape-app
    build: .
    restart: always
    ports: 
      - "5173:5173"
    expose:
      - "5173"
    command: pnpm dev

    volumes:
      - .:/src/usr/app
      - /src/usr/app/node_modules
