services:
  client:
    container_name: surfscrape-app
    build: ./client/
    restart: always
    ports: 
      - "5173:5173"
    expose:
      - "5173"
    command: pnpm dev

    volumes:
      - ./client:/src/usr/app
      - /src/usr/app/node_modules
  api:
    container_name: surfscrape-api
    build: ./server/
    restart: always
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    command: pnpm dev

    volumes:
      - ./server:/src/usr/app
      - /src/usr/app/node_modules
